# Generated by Django 5.2.1 on 2025-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(default='Teste', max_length=20),
            preserve_default=False,
        ),
    ]
