# Generated by Django 5.2.1 on 2025-06-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0002_mensagem_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
