# Generated by Django 5.2.1 on 2025-06-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0003_delete_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pegadacarb',
            name='valorTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
