# Generated by Django 5.2.1 on 2025-06-11 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0004_alter_pegadacarb_datare_alter_pegadacarb_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 11, 11, 59, 54, 720542, tzinfo=datetime.timezone.utc)),
        ),
    ]
