# Generated by Django 5.2.1 on 2025-06-12 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0005_alter_pegadacarb_datare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 17, 49, 28, 191542, tzinfo=datetime.timezone.utc)),
        ),
    ]
