# Generated by Django 5.2.1 on 2025-06-23 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0006_alter_pegadacarb_datare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 23, 11, 29, 26, 873732, tzinfo=datetime.timezone.utc)),
        ),
    ]
