# Generated by Django 5.2.1 on 2025-06-16 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0007_alter_pegadacarb_datare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 11, 28, 29, 261656, tzinfo=datetime.timezone.utc)),
        ),
    ]
