# Generated by Django 5.2.1 on 2025-06-24 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0008_alter_pegadacarb_datare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 24, 13, 0, 44, 361489, tzinfo=datetime.timezone.utc)),
        ),
    ]
