# Generated by Django 5.2.1 on 2025-06-24 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcarb', '0009_alter_pegadacarb_datare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegadacarb',
            name='dataRe',
            field=models.DateField(default=datetime.datetime(2025, 6, 24, 14, 10, 3, 491923, tzinfo=datetime.timezone.utc)),
        ),
    ]
