# Generated by Django 5.2.1 on 2025-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
