# Generated by Django 5.2.1 on 2025-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_cadastro_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pessoa',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
