# Generated by Django 5.2.1 on 2025-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('near_term_status', models.CharField(max_length=100)),
                ('near_term_target_year', models.CharField(max_length=100)),
            ],
        ),
    ]
