# Generated by Django 5.2.1 on 2025-06-25 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='Emp_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
